name: DITA Open Toolkit
safe: true
lsi: false
highlighter: rouge
markdown: kramdown
baseurl: ""
sass:
    style: compressed
    sass_dir: css
exclude: ["gulpfile.js", "package.js", "node_modules", "images/dita-ot_input-output.graffle"]

# Major & minor release version (2 digits)
release: "3.0"
# Maintenance version (normally 3 digits, 2 for initial minor release)
version: "3.0"

# Enable redirects (#43)
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
