name: DITA Open Toolkit
safe: true
lsi: false
highlighter: rouge
markdown: kramdown
baseurl: "/dita-ot.github.io"
sass:
    style: compressed
    sass_dir: css
exclude: ["gulpfile.js", "package.js", "node_modules", "images/dita-ot_input-output.graffle"]

# MAJOR.MINOR
release: "2.3"
# MAJOR.MINOR.BUG
version: "2.3.3"
